//
//  BuilderDSLTests.swift
//  BeepingTests
//
//  Tests for the BEE-72 builder DSL: `BeepingClient.local()` /
//  `.cloud(apiKey:endpoint:)` static factories returning a chainable
//  `BeepingClientBuilder`.
//

import Testing
import Foundation
@testable import Beeping

@Suite("BeepingClient builder DSL (BEE-72)")
struct BuilderDSLTests {

    // MARK: - Helpers

    private func mockedSession(
        responder: @escaping @Sendable (URLRequest) -> (Data, HTTPURLResponse)
    ) -> URLSession {
        let config = URLSessionConfiguration.ephemeral
        config.protocolClasses = [MockURLProtocol.self]
        MockURLProtocol.responder = responder
        return URLSession(configuration: config)
    }

    private func samplePayload() -> BeepingPayload {
        BeepingPayload(
            key: "12345",
            decodedString: "12345abcd",
            mode: 2,
            timestamp: 99,
            confidence: 0.8,
            confidenceError: 0.1,
            confidenceNoise: 0.2,
            receivedBeepsVolume: -5
        )
    }

    // MARK: - Static factory methods

    @Test("BeepingClient.local() returns a builder")
    func localReturnsBuilder() {
        let builder: BeepingClientBuilder = BeepingClient.local()
        _ = builder
    }

    @Test("BeepingClient.cloud(apiKey:endpoint:) returns a builder")
    func cloudReturnsBuilder() {
        let builder: BeepingClientBuilder =
            BeepingClient
            .cloud(apiKey: "test", endpoint: URL(string: "https://api.beeping.io")!)
        _ = builder
    }

    @Test("Builder is Sendable (compile-time gate)")
    func builderIsSendable() {
        func requireSendable<T: Sendable>(_ x: T) {}
        requireSendable(BeepingClient.local())
    }

    // MARK: - Build path

    @Test("Local builder .build() produces a working client")
    func localBuilderBuilds() async {
        let client = BeepingClient.local().build()
        _ = client
        await client.close()
    }

    @Test("Cloud builder .build() produces a client whose send() goes through URLSession")
    func cloudBuilderBuildsAndUsesSession() async throws {
        MockURLProtocol.reset()
        defer { MockURLProtocol.reset() }

        // Minor twist: BeepingClientBuilder.encoderFactory closes over a
        // fresh CloudEncoder using `URLSession.shared`, so we can't
        // directly inject our mocked session through the public API in
        // BEE-72. We exercise the cloud-builder path by verifying that
        // the resulting client is constructible and configured.
        // Full HTTP round-trip via the builder is verified separately
        // when BEE-73 lands the OpenAPI client (which DOES support
        // session injection in its public API).
        let client =
            BeepingClient
            .cloud(apiKey: "k", endpoint: URL(string: "https://api.beeping.io")!)
            .build()
        _ = client
        await client.close()
    }

    // MARK: - Fluent chain preserves settings

    @Test("Fluent chain preserves mode + logLevel + telemetryEnabled")
    func fluentChainPreservesSettings() async {
        let client = BeepingClient.local()
            .mode(.audible)
            .logLevel(.debug)
            .telemetryEnabled(true)
            .build()

        // Internal accessors (testable import) verify the config
        // landed on the actor.
        let logLevel = await client.logLevel
        let telemetryEnabled = await client.telemetryEnabled
        #expect(logLevel == .debug)
        #expect(telemetryEnabled == true)
        await client.close()
    }

    @Test("Default builder values: logLevel .info, telemetry off")
    func defaultBuilderValues() async {
        let client = BeepingClient.local().build()
        let logLevel = await client.logLevel
        let telemetryEnabled = await client.telemetryEnabled
        #expect(logLevel == .info)
        #expect(telemetryEnabled == false)
        await client.close()
    }

    // MARK: - traceID wiring (BEE-2309)

    @Test(".traceID(_:) propagates the injected id to the client")
    func builderTraceIDPropagates() async {
        let client =
            BeepingClient
            .cloud(apiKey: "k", endpoint: URL(string: "https://api.beeping.io")!)
            .traceID("abc123")
            .build()
        let trace = await client.traceID
        #expect(trace == "abc123")
        await client.close()
    }

    @Test("Without .traceID the client autogenerates a non-empty id")
    func builderTraceIDDefaultsAutogenerated() async {
        let client = BeepingClient.local().build()
        let trace = await client.traceID
        #expect(trace.isEmpty == false)
        await client.close()
    }

    // MARK: - BeepingLogLevel

    @Test("BeepingLogLevel cases match the documented set (BEE-74 expanded to 7)")
    func logLevelCases() {
        // BEE-74 added .fault + .trace to the original BEE-72 set.
        let all: [BeepingLogLevel] = [.off, .fault, .error, .warn, .info, .debug, .trace]
        _ = all
    }

    @Test("BeepingLogLevel is Sendable + Equatable")
    func logLevelSendable() {
        func requireSendable<T: Sendable>(_ x: T) {}
        requireSendable(BeepingLogLevel.debug)
        #expect(BeepingLogLevel.info == .info)
    }
}
