//
//  CloudEncoder.swift
//  Beeping
//
//  `BeepingEncoder` strategy that routes encoding through `beepbox-server`
//  via `URLSession`. Type-safe Codable types live in
//  `BeepboxAPITypes.swift` and mirror the OpenAPI spec at
//  `OpenAPI/openapi.yaml` (vendored from `beepbox-server`).
//
//  Endpoint contract (per spec):
//
//    POST {endpoint}/v1/encode
//    Headers:
//      Authorization: Bearer <apiKey>           (Apple HTTP scheme bearer)
//      Content-Type:  application/json
//    Body:
//      EncodeRequest { key, mode?, sampleRate?, duration?, start?,
//                      interval?, volumeBeeps? }
//    Responses:
//      200 audio/wav          → server accepted; body is the encoded WAV
//      400 ValidationErrorResponse
//      429/500 ErrorResponse
//
//  BEE-2050 wires the response WAV through `WAVPlaybackSink` so the
//  bytes are actually rendered to the speaker — that completes the
//  Send → audio → Receive round-trip for cloud mode. The sink defaults
//  to `AVAudioPlayerSink`; tests inject a spy.
//

import Foundation

internal actor CloudEncoder: BeepingEncoder {
    private let apiKey: String
    private let endpoint: URL
    private let session: URLSession
    private let playbackSink: any WAVPlaybackSink
    private let mode: BeepingMode
    /// Trace-ID sent as the `X-Trace-Id` request header for end-to-end
    /// correlation with server logs (BEE-2309). Defaults to an
    /// autogenerated id; the builder wires the client's shared trace-ID
    /// through so SDK logs and the wire request share one id.
    private let traceID: String
    /// Optional in-app loopback decoder. When set, the WAV bytes are
    /// fed through it after playback so the listener emits a `.decoded`
    /// event for the cloud-emitted beep without needing speaker→mic
    /// acoustic round-trip (which doesn't loop on iOS Simulator).
    /// `BeepingClientBuilder` wires this up automatically with the
    /// listener's wrapper so events flow through the same stream.
    private let loopbackWrapper: BeepingCoreWrapper?

    internal init(
        apiKey: String,
        endpoint: URL,
        session: URLSession = .shared,
        playbackSink: (any WAVPlaybackSink)? = nil,
        mode: BeepingMode = .all,
        loopbackWrapper: BeepingCoreWrapper? = nil,
        traceID: String = BeepingLog.generateTraceID()
    ) {
        self.apiKey = apiKey
        self.endpoint = endpoint
        self.session = session
        self.playbackSink = playbackSink ?? AVAudioPlayerSink()
        self.mode = mode
        self.loopbackWrapper = loopbackWrapper
        self.traceID = traceID
    }

    func encode(_ payload: BeepingPayload) async throws {
        let url = endpoint.appendingPathComponent("v1/encode")
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("Bearer \(apiKey)", forHTTPHeaderField: "Authorization")
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        // BEE-2309: end-to-end trace correlation. Same id the os.Logger tags.
        request.setValue(traceID, forHTTPHeaderField: "X-Trace-Id")
        request.httpBody = try Self.encodeBody(payload: payload, mode: mode)

        // BEE-2308: transport failures (timeout, DNS, connection reset)
        // surface as `networkError(statusCode: nil)` — they never reached
        // an HTTP response, so there is no status to report.
        let data: Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch {
            throw BeepingError.networkError(statusCode: nil)
        }

        guard let http = response as? HTTPURLResponse else {
            throw BeepingError.networkError(statusCode: nil)
        }

        guard (200..<300).contains(http.statusCode) else {
            throw Self.mapErrorResponse(http)
        }

        // BEE-2050: hand the response WAV to the playback sink so the
        // device renders it through the speaker. Default sink is
        // `AVAudioPlayerSink`; tests inject a spy.
        try await playbackSink.play(wavData: data)

        // BEE-2050: feed the same WAV through a dedicated decoder on
        // the listener's wrapper so the local stream emits a `.decoded`
        // event in the same app, even on iOS Simulator where the mic
        // doesn't loop back from the speaker. On a physical device this
        // also fires synchronously alongside whatever the mic decodes
        // through the air — both arrive at the consumer's stream.
        loopbackWrapper?.decodeLoopback(wav: data, mode: mode)
    }

    // MARK: - Helpers

    private static let jsonEncoder: JSONEncoder = {
        let e = JSONEncoder()
        e.outputFormatting = [.sortedKeys]
        return e
    }()

    private static func encodeBody(payload: BeepingPayload, mode: BeepingMode) throws -> Data {
        // The OpenAPI spec takes a 5-char `key`. BeepingPayload exposes
        // `key` directly; the 9-char `decodedString` is metadata-y (key
        // + 4-char base32 timestamp) used by the local engine but
        // server-side the timestamp is generated server-side.
        //
        // Mode propagation: server defaults to `inaudible` if the field
        // is omitted (~17.8 kHz carrier), which most laptop speakers
        // can't reproduce. Map the SDK's `BeepingMode` to the server's
        // smaller enum so the builder's `.mode(...)` reaches the wire.
        let body = EncodeRequest(key: payload.key, mode: serverMode(from: mode))
        return try jsonEncoder.encode(body)
    }

    // Exposed (internal) for property-based tests in BEE-76 that verify
    // the mapping is a total function over `BeepingMode`.
    internal static func serverMode(from mode: BeepingMode) -> EncodeRequest.Mode {
        switch mode {
        case .audible, .audibleOld: return .audible
        case .nonAudible, .nonAudibleOld: return .inaudible
        case .all, .custom: return .all
        }
    }

    // BEE-2308: map a non-2xx HTTP response to a typed `BeepingError`,
    // mirroring the Android contract (`AuthenticationFailed` /
    // `RateLimited(retryAfter)` / `NetworkError(statusCode)`). The server's
    // error body is no longer threaded into the error — the typed cases
    // carry only the status code (and `Retry-After` for 429), which is what
    // `beeping_flutter` (BEE-86) consumes. `decoderInternal` is reserved for
    // real decoder/encoder failures and is never produced here.
    internal static func mapErrorResponse(_ http: HTTPURLResponse) -> BeepingError {
        switch http.statusCode {
        case 401, 403:
            return .authenticationFailed
        case 429:
            return .rateLimited(retryAfter: retryAfter(from: http))
        default:
            return .networkError(statusCode: http.statusCode)
        }
    }

    /// Parses the `Retry-After` header as delta-seconds. Returns `0` when
    /// the header is absent or not a valid number. (HTTP also permits an
    /// absolute HTTP-date form; the beepbox server only emits delta-seconds,
    /// so the date form is intentionally unsupported.)
    private static func retryAfter(from http: HTTPURLResponse) -> TimeInterval {
        guard let raw = http.value(forHTTPHeaderField: "Retry-After"),
            let seconds = TimeInterval(raw.trimmingCharacters(in: .whitespaces))
        else {
            return 0
        }
        return seconds
    }
}
